### ISSUE TITLE
steward fails and loop over alert

### ISSUE THREAD

**Issue by solsticedhiver** [TheThingSystem/steward#285]
bear with me as I am a *newbie* with *steward*, just trying to run it. I just finished the manual installation of dependacies on ubuntu.

And when I run `sudo ./run.sh`, first I have that error about node: "node: command not found"
So I had to tweak *run.sh* to add a function called node to call the binary **nodejs** because *node* is installed as **nodejs** on *ubuntu*. Go figure.

To the point, now that it runs, I have that alert:

     alert: [steward] exception diagnostic=Cannot call method 'slice' of null
     alert: [steward] exception stack=[{"fileName":"/home/solstice/prog/dvcs/steward/steward/devices/devices-media/media-video-appletv.js","lineNumber":206,"functionName":"Browser.mdns.createBrowser.on.on.discovery.debug.event","typeName":"Browser","methodName":"mdns.createBrowser.on.on.discovery.debug.event","columnNumber":64,"native":false},{"fileName":"events.js","lineNumber":98,"functionName":"Browser.EventEmitter.emit","typeName":"Browser","methodName":"EventEmitter.emit","columnNumber":17,"native":false},{"fileName":"/home/solstice/prog/dvcs/steward/steward/node_modules/mdns/lib/browser.js","lineNumber":31,"functionName":"on_resolver_done","typeName":"Object","methodName":null,"columnNumber":14,"native":false},{"fileName":"/home/solstice/prog/dvcs/steward/steward/node_modules/mdns/lib/browser.js","lineNumber":94,"functionName":"next","typeName":"Object","methodName":null,"columnNumber":7,"native":false},{"fileName":"[as 2] (/home/solstice/prog/dvcs/steward/steward/node_modules/mdns/lib/resolver_sequence_tasks.js","lineNumber":160,"functionName":"Array.makeAddressesUnique","typeName":"Array","methodName":"makeAddressesUnique","columnNumber":5,"native":false},{"fileName":"/home/solstice/prog/dvcs/steward/steward/node_modules/mdns/lib/browser.js","lineNumber":97,"functionName":"next","typeName":"Object","methodName":null,"columnNumber":21,"native":false},{"fileName":"/home/solstice/prog/dvcs/steward/steward/node_modules/mdns/lib/resolver_sequence_tasks.js","lineNumber":143,"functionName":null,"typeName":null,"methodName":null,"columnNumber":11,"native":false},{"fileName":"/home/solstice/prog/dvcs/steward/steward/node_modules/mdns/lib/resolver_sequence_tasks.js","lineNumber":117,"functionName":"Object.wrap.oncomplete","typeName":"Object","methodName":"wrap.oncomplete","columnNumber":9,"native":false}]
     uncaught exception: TypeError: Cannot call method 'slice' of null
   
It waits 10 seconds and restart and fails again, over and over...

And I don't get anything running on `http://locahost:8887`

Edit: I thought of a bug but may be it's my installation of steward that is incomplete/incorrect /o\

**Comment by solsticedhiver** [comment]
Whatever way I try to install *node* and *npm*, I always get eror when running `npm install -l` from within stard directory about building module.

I tried, using node.js official linux 64 bit binary, using deb.nodesource.com packages, official ubuntu nodejs package (15.04 vivid 64 bits)

I always get error with *socket.io* and in the other case, even more build errors.

So I guess it's the installation of steward **depedancies** that fails, not strictly steward....

**Comment by mrmakeit** [comment]
What version of node are you using?  `node -v`
