### ISSUE TITLE
Could not find package hidapi

### ISSUE THREAD

**Issue by arcturus** [TheThingSystem/steward#292]
When doing `npm install` on macosx I get the following error:

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/hidapi
npm ERR! 404
npm ERR! 404 'hidapi' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'node-hid'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

There is no hdipai package on the registry.

**Comment by mrmakeit** [comment]
A fix for that was pushed earlier. Do you have the latest master?

**Comment by arcturus** [comment]
Got it resolved, downgraded my nodejs version to v0.10.24
